### ISSUE TITLE
Blacklist Filter for Tags is Not Case Sensitive

### ISSUE THREAD

**Issue by Fujosej** [kwaschny/unwanted-twitch#102]
I've noticed that the blacklist filter for tags isn't functioning as expected in regards to case sensitivity. Currently, if I add a tag with a capital letter, such as "Deutsch", it won't get filtered and will still show up in the search results.
To ensure that all variations of the language are filtered, I need to add both "deutsch" and "Deutsch" to the blacklist.

Thanks!

**Comment by kwaschny** [comment]
I cannot reproduce this [and the source code backs me up](https://github.com/kwaschny/unwanted-twitch/blob/master/scripts/directory.js#L1236). Would you please provide step by step instructions how you are able to reproduce this behavior?

**Comment by Fujosej** [comment]
If I wanted to add this tag manually, as in the screenshot below, it wouldn't appear in the list of blacklisted tags.
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/216349706-985e2c80-106a-4b50-afa6-c3512863ac7f.png)
</details>

Also, I noticed that you can't blacklist tags directly from the channel page, that would be a good option because in a browsing page not every tag is visible.
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/216350710-a2e928ab-45d2-4779-aeff-40defbfd4f9e.png)
</details>

**Comment by kwaschny** [comment]
> it wouldn't appear in the list of blacklisted tags.

Because any input will be normalized before adding it to the blacklist. `Deutsch` is normalized to `deutsch` and thus will not appear again. Working as intended.

> I noticed that you can't blacklist tags directly from the channel page

If you can see the "X" button on the top right of the channel, then the item tag detection is broken on your end. This is most likely also the reason why the tag normalization appears broken.

So, why is it broken? I don't know. It still works on my end, so I usually assume that you are on a canary build of twitch.tv, which occassionally happens to some users (basically Twitch testing new features).

**Comment by kwaschny** [comment]
> it wouldn't appear in the list of blacklisted tags.

Because any input will be normalized before adding it to the blacklist. `Deutsch` is normalized to `deutsch` and thus will not appear again. Every tag will be normalized before being compared/matched against the blacklist.

> I noticed that you can't blacklist tags directly from the channel page

Are you referring to the channel page where the actual stream video is shown? That page is simply not supported.

----

Is blocking of other tags and channels working for you?

**Comment by Fujosej** [comment]
> Because any input will be normalized before adding it to the blacklist. `Deutsch` is normalized to `deutsch` and thus will not appear again. Every tag will be normalized before being compared/matched against the blacklist.

Because of this limitation, I am unable to add a variation of a tag to the blacklist, which is why streams with tags starting with the uppercase "D" in "Deutsch" are appearing in the browsing page. Ideally, I would like to blacklist both "Deutsch" and "deutsch" to avoid both tags at once.


> Are you referring to the channel page where the actual stream video is shown? That page is simply not supported.

Yes 
I'd like to have the ability to blacklist tags directly from the channel page where the streaming video is displayed. This would be useful because there may be some tags that are not showing up in the browsing page. Is it possible to add this feature?


> Is blocking of other tags and channels working for you?

Everything else seems to work flawlessly. Thanks!

**Comment by kwaschny** [comment]
> Because of this limitation

It's **not** a limitation. Every item is normalized and then compared. Adding `DêUtșČH` to your blacklist is normalized to `deutsch`. If there are channels on the directory with the tags `Deutsch`, `deutsch`, `DéUtsčḤ`, **all of them** match because **all of them are normalized** to `deutsch` and then compared to `deutsch`.

If channels with any variation of `Deutsch` are not blocked on your end, the tags on the channels were most likely not detected to begin with. Thus they cannot be matched against your blacklist, regardless of what your blacklist contains.

I unfortunatelly cannot help you unless I can reproduce it (and I can't). If you are up for the challenge, [use a local version with debug flag set and check if tags are detected properly](https://github.com/kwaschny/unwanted-twitch/blob/master/CONTRIBUTING.md#setting-up-the-extension-for-debugging).

**Comment by Fujosej** [comment]
Okay, thanks. I understand now. I didn't realize what normalization means.

So while I was browsing, a channel with a blacklisted tag sneaked in, it was in Portugues language and it should have been blocked by the extension because I have "portugues" blacklisted.
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/216679939-1911f846-7225-4bd1-a099-d5a04bab41ff.png)

</details>
The channel was using the version of the tag "Português", so in theory, it should have been normalized and blacklisted as "portugues". But what I found in the browsing section is that only three tags were shown.
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/216680082-f8b2fbac-dffd-4079-96d5-ef9d11e1cd07.png)
</details>

So what I'm getting at is that for some odd reason, the "Português" tag was omitted from the browsing section of Twitch. On the channel page, you can clearly see that tag being shown.
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/216680493-48922538-20af-44bd-910f-c0c0e58d8ed0.png)
</details>

At first, I thought that maybe I was browsing at 150% zoom in Chrome, but I don't think that's causing issues with tags being displayed or not. Even at 100% zoom, Twitch still shows a limited number of tags in the browsing section.

I am also using FrankerFaceZ extension and TwitchPreviews.

**Comment by kwaschny** [comment]
Aha! Very good observation! Now that explains why the channel is not being blacklisted: the blacklisted tag might not show up in the overview item. And if the tag isn't visible to the extension, it cannot be matched against the blacklist. Thus some channels are blocked and some are not, depending on the number of tags and if these are visible. There seems to be a hard limit of 3 tags per item.

Thank you for the report. The bad news: I cannot fix this because the extension can only access the DOM (what you see in the browser) and not the full stream info. 😕
