### ISSUE TITLE
Firefox Extension appears to no longer be working

### ISSUE THREAD

**Issue by aprovoast** [kwaschny/unwanted-twitch#108]
Sometime recently the extension no longer appears to work. 
Extension shows as active in firefox, but all functionality appears to be gone, including filtering and UI elements.

**Comment by ma7dev** [comment]
It seems that there is a new UI for Twitch. It also doesn't work on Chrome.

**Comment by kwaschny** [comment]
It still works on my end except the frontpage. I assume it's a partial rollout where it takes up to two weeks before everyone can see the new layout. Are all views affected? Can you provide screenshots?

**Comment by MrBeldin** [comment]
![image](https://github.com/kwaschny/unwanted-twitch/assets/134392981/bb02beee-c167-413e-bd23-d05ce419064f)

This is what the category layouts currently look like. An "ad-free preview" added to the top (there's a built-in options menu to turn that off, so that's not a problem). Thumbnails seem to have a fair bit of changes as well; if the said preview is on, the currently previewed stream has a white background, and the stream title scrolls on mouseover if it doesn't fully fit under the thumbnail. "Manage Blacklist" button doesn't show up at all and blacklisted channels are coming through.

Browse > Categories seems to work fine for filtering out blacklisted categories.

**Comment by MrBeldin** [comment]
> Yeah, they seem to have reset it back to normal after midnight. I think everything didn't work as they seemed to change the entire website structure.

New layout is still visible here, so it's not back to normal. Could be caching issues or such, causing it to go on and off until it rolls out fully everywhere.

As a workaround, if I really want to hide some channels until the extension is updated, I simply add a _twitch.tv##.bwZaon:has-text(Channel_Name)_ filter to uBlock Origin. That seems to work for now.

**Comment by aprovoast** [comment]
> It still works on my end except the frontpage. I assume it's a partial rollout where it takes up to two weeks before everyone can see the new layout. Are all views affected? Can you provide screenshots?

![image](https://github.com/kwaschny/unwanted-twitch/assets/134338304/daa1113a-967d-4d25-9761-18c93b40c207)

It looks like it's disabled on the front page,but  it still seems to be active on the 'Following' and 'Browse' Tabs.

![image](https://github.com/kwaschny/unwanted-twitch/assets/134338304/a0fe315f-8fd3-4ef6-bd78-f35c5e8df3db)

**Comment by LockeBirdsey** [comment]
Filtering also stopped working on the sidebar, no matter which page you're on.

**Comment by kwaschny** [comment]
> It looks like it's disabled on the front page

Frontpage stopped working because Twitch decided to keep a placeholder element at the bottom of the page which makes the extension think that the page has not been fully loaded yet. I added a cap to prevent infinite waiting.

> Filtering also stopped working on the sidebar, no matter which page you're on.

I checked that and wasn't able to reproduce it.

> New layout is still visible here, so it's not back to normal.

I still don't have it and last time they added the ad-free preview slider, they never rolled it out for everyone.

> Could be caching issues or such, causing it to go on and off until it rolls out fully everywhere.

Experimental features are (account) flags. They are stored in in `window.__twilightSettings`.

**Comment by Mobyclick2034** [comment]
First this extension is great thank you for your time. Now the problem I am having. week or so it stopped working. on the pages Following, Main page and Browse work with the X for blacklist. If I click a specific channel X is not available on any of the channel boxes.

**Comment by Mobyclick2034** [comment]
I appreciate what everyone does and will wait for the update. I so love the use of the extension. Thank you for your hard work and help to the community.

**Comment by kwaschny** [comment]
Looks like it's finally being rolled out.

**Comment by ProditorMagnus** [comment]
Curiously twitch switched me now back to old version, the one where extension still works.

**Comment by kwaschny** [comment]
> Curiously twitch switched me now back to old version [...]

Same. Luckily my other (test) account still has the new layout. So I was able to add the new selectors without breaking the old ones. **The new version has been submitted and will release soon.**

I also migrated to the new manifest (v3), so **Firefox users will need to update to at least Firefox 109** (from January 2023).

**Comment by kwaschny** [comment]
Firefox version is also live by now.

For some reason, Microsoft Edge rejected my submission, so there won't be any update to the Edge version for now. ¯\\_(ツ)_/¯
