### ISSUE TITLE
Add a way to block empty categories

### ISSUE THREAD

**Issue by chinmaymodi** [kwaschny/unwanted-twitch#117]
Occasionally I see streams of content types I have blocked because they have not added a category. Is there a way to block these? If not, could it be implemented?

Chrome 119.0.6045.160
UT 23.10.17
Other twitch extensions: 7tv/bttv
![image](https://github.com/kwaschny/unwanted-twitch/assets/8926948/f1f4a85e-77c9-42cb-826f-8ca2d32ef479)

**Comment by kwaschny** [comment]
The problem here is how "no category" is presented in the UI. There is no way of knowing if the category is not set or simply absent due to the view itself (since not all pages show the category in the channel tile). Generally blocking items with an unknown category would lead to false positives. The only solution would be tracking where the category is supposed to show.

No easy solution here.

**Comment by chinmaymodi** [comment]
Ah, I see, no easy solution then, thank you for the response and for the addon!
