### ISSUE TITLE
Extension not working on Waterfox?

### ISSUE THREAD

**Issue by notNSANE** [kwaschny/unwanted-twitch#3]
Hi, I tried this extension on latest Waterfox portable: https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_56.2.2_English.paf.exe

But nothing appears on the address bar or on Twitch.

Maybe it's just incompatible with this version which is using an old Firefox source?

**Comment by kwaschny** [comment]
Waterfox doesn't support [page_action.show_matches](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action) yet, which is required to detect if a tab is on twitch.tv and make the extension do its work.

> Reading manifest: Error processing page_action.show_matches: An unexpected property was found in the WebExtension manifest.

[The first version](https://addons.mozilla.org/de/firefox/addon/unwanted-twitch/versions/?page=1#version-18.9.1) ([source code](https://github.com/kwaschny/unwanted-twitch/blob/master/publish/firefox/18.9.1.zip)) was working with the `tabs` permission to detect twitch.tv instead of relying on `page_action.show_matches`. And although this old version properly loads in Waterfox, there seem to exist other issues.

Sorry to say, but there's little reason for me to support older [Gecko engines](https://en.wikipedia.org/wiki/Gecko_(software)).

**Comment by notNSANE** [comment]
No probs! I understand why you don't want to support it. Interesting issue, I though they could be applied globally. I guess I should wait for Waterfox to upgrade.

Cheers and thanks for this extension!
