### ISSUE TITLE
Hiding all streams without a game/category set

### ISSUE THREAD

**Issue by PhiZero** [kwaschny/unwanted-twitch#47]
Hello,

Issue https://github.com/kwaschny/unwanted-twitch/issues/19 talked about filtering out streams with "Untitled Broadcast" or no category specified. 

Would it still be possible to filter out the streams without a category? I'm indeed using the low to high sorting, and it's a bit of a hassle going through the sea of 0 viewer streams without a game set.

**Comment by kwaschny** [comment]
The problem is: The extension doesn't necessarily know when to expect game/category on the stream card. Some views have it, some do not. If it hides on spec, the filtering will be very prone to unexpected "hides everything"-behavior. It's not impossible to implement, but it will cause more harm than good.

On that note: filtering based on number of current viewers. The extension just isn't suited for mass filtering as the information/content should be filtered before arriving at the client/browser. It would just end up being a "wait for the first stream to stay visible" when ordering by lowest to highest viewers.

**Comment by WJCra** [comment]
Hm, I see. Do you have any other ideas how to filter past the sea of 0-viewer streams or no-category streams? Or would you just recommend to not use the low to high sort mode?

**Comment by kwaschny** [comment]
As far as I can tell, [even the (server-side) API](https://dev.twitch.tv/docs/api/reference#get-streams) doesn't allow you to filter by viewers. You would just have to paginate through hundreds of streams filtering the stream properties to get what you want.

Out of interest: What's your goal? Find streams with low viewer count, except the ones with 0 or no game set?

**Comment by WJCra** [comment]
Yeah, I prefer watching smaller streamers. But there's a plethora of 0-viewer streams (hundreds?) and streams where the game isn't set. I'd just like to filter those out since it's often the case that those streams don't have anything interesting (russian anime streams, sports, dead air, etc etc).

And, yeah. That link is pretty handy. I'm assuming having something like that in the plugin is outside the scope of your project, correct?

**Comment by kwaschny** [comment]
See [project status](https://github.com/kwaschny/unwanted-twitch#project-status).
