### ISSUE TITLE
Hide streams based on viewer count

### ISSUE THREAD

**Issue by ChipWolf** [kwaschny/unwanted-twitch#49]
Sometimes you don't want to see streams with either too low or too high of a viewer count, a feature which would allow you to configure this would be awesome

**Comment by ChipWolf** [comment]
I wrote a little snippet for `readChannel` which works nicely, I'm not a Javascript expert so it could likely be optimized. I may produce a PR later on

```js
    /* BEGIN: viewers */
    buffer = parent.querySelector('.tw-media-card-stat p');

    if (buffer) {

        let stat = buffer.textContent;

        if (stat.includes(' viewers')) {

            let viewers = stat.replace(' viewers', '');

            if (Number.isInteger(Number(viewers))) {

                result.viewers = Number(viewers);

            } else if (Number.isFinite(Number(viewers.slice(0, -1)))) {

                switch (viewers.slice(-1)) {

                    case 'K':
                        result.viewers = Number(viewers.slice(0, -1)) * 1e3;
                        break;
                    case 'M':
                        result.viewers = Number(viewers.slice(0, -1)) * 1e6;
                        break;

                    default:
                        console.log('oh no it die');
                }

            }


        }


        console.log('viewers of channel', result.viewers, node)

    } else {

        return console.log('Unable to determine viewers of channel.', node);
    }

    /* END: viewers */
    ```

**Comment by kwaschny** [comment]
I [already mentioned](https://github.com/kwaschny/unwanted-twitch/issues/47#issuecomment-758871471) that filtering based on viewers will often end up in "wait for the first stream to stay visible". You fetch 20 channels, filter them, fetch the next 20 channels, filter them etc. If you order by highest/lowest and have the opposite viewer count desire, you are in for a bad time. Also, this would probably trigger the mass-fetch detection they recently implemented as an anti-bot measurement.

Anyway, you will also have to integrate an input control to adjust the viewers value on every page/view. I'm pretty sure people have different thresholds for different games/categories, so take that into account as well.

Your snippet doesn't take localization into account. Better detect any number and extract it (instead of requiring a word such as `viewers`). I also need to parse the number locale-sensitive, 12345 could be `12,345` or `12.345` depending on the browser's locale.

**Comment by ChipWolf** [comment]
@kwaschny; so essentially just regex anything out except integers, and keep an eye on the sort option?

```js
let viewers = buffer.textContent.replace(/\D+/g, '')
```

**Comment by kwaschny** [comment]
@ChipWolf
[I wrote a unit test with 78 assertions](/kwaschny/unwanted-twitch/blob/%2349/tests/units.html) for you.
Your initial implementation would fail 55 assertions.
Your latest proposal would still fail 39 assertions.

If you want to work on this feature, feel free to reopen the issue.
