### ISSUE TITLE
It stops working after a while

### ISSUE THREAD

**Issue by 7Soul** [kwaschny/unwanted-twitch#52]
I used this extension for a few days, then it stopped working. It says it's enabled, the icon shows color, and it has access to twitch but it doesn't work anymore. Clicking disable doesn't do anything, manually changing the blacklist, saving, exporting, importing and changing between local/cloud also doesn't do anything

I removed it and reinstalled and it worked for a while (though I imported my blacklist and it wouldn't save, both in local or cloud mode) then it stopped working again after a day or two. None of the buttons or options get saved or do anything. Like if I uncheck the "Show X buttons", when I click the extension it's checked again

**Comment by kwaschny** [comment]
Interesting. Sounds like the browser doesn't let the extension save anything. What browser and what version are you using? Did you recently change any settings or installed new extensions in your browser? Do other extensions, that store information, still work? Can you temporarily disable all other extensions and only run this extension (restart browser in between)? Would you mind testing the extension on a different browser?

You can also help debugging the issue by checking if the developer console of your browser reports anything. To do that, keep the extension installed/enabled, go to the Twitch website, press the `F12` key and visit the `Console` tab. Does it show anything? The extension logs issues starting with `UTTV`. (You can ignore errors stating `ERR_BLOCKED_BY_CLIENT` (Chrome) or not being able to load `<script>` blocks (Firefox) - that's usually just your adblock extension doing its work.)

**Comment by kivle** [comment]
These last few days the extension has stopped working for me as well. I see the following stack trace in the console:

Uncaught ReferenceError: logTrace is not defined
    at getCurrentPage (chrome-extension://egbpddkgpjmliolmpjenjomflclekjld/scripts/directory.js:166)
    at chrome-extension://egbpddkgpjmliolmpjenjomflclekjld/scripts/directory.js:51

**Comment by kivle** [comment]
I see in the manifest that you have two separate content_scripts defined. The one with directory.js does not include the common.js script where the logTrace function is defined. Could it be that my computer randomly loads the two content scripts in a different order, and because of that it fails maybe?

**Comment by kwaschny** [comment]
The `content_scripts` are supposed to load in order according to the official docs. It doesn't mention how multiple entries with the same `matches` are treated though. So you could be right, maybe it is a rare race condition that is happening here. I cannot reproduce the problem, but I also don't see any reason to not merge the entries right now.

Can you @kivle and @7Soul please [test this temporary version (Chrome/Edge)](https://github.com/kwaschny/unwanted-twitch/blob/%2352/publish/chrome/21.3.11.zip?raw=true), i.e. [(Firefox)](https://github.com/kwaschny/unwanted-twitch/blob/%2352/publish/firefox/21.3.11.zip?raw=true)?

Disable the current extension and then load the downloaded one via `chrome://extensions/` on Chrome (tick dev mode checkbox top right first), `edge://extensions/` on Edge (tip dev mode checkbox bottom left first) or `about:debugging#/runtime/this-firefox` on Firefox (top button, make sure to open twitch.tv in a separate window (not just a separate tab!) as it causes a communication conflict otherwise).

Thank you for helping.

**Comment by kivle** [comment]
I have done a quick test and it does seem to fix the problem for me. Before the fix basically none of the UI elements related to the extension would show up at all for me, but now they do. Now everything shows up and seems to work as expected. Thanks for looking into it. :)

**Comment by 7Soul** [comment]
Thanks for the quick response, I'll try this version out and report back in a few days (since like I said it usually works for a while). To answer to your previous question, this was the last extension I've installed, and I also have Keyword Blocker for Youtube which has the same functionality as this one and never had any issues

**Comment by 7Soul** [comment]
Almost forgot about this! Seems to be working, thanks for the help

**Comment by kwaschny** [comment]
Thank you for the feedback. I will deploy the fix on the extension stores today.
