### ISSUE TITLE
Doesn't seem to be working on Browse: Categories

### ISSUE THREAD

**Issue by djcline23** [kwaschny/unwanted-twitch#72]
I'm currently not seeing the Xs on Browse: Categories, and it is also not filtering games I have on my black list. Using chrome.

**Comment by kwaschny** [comment]
Duplicate of #71 ? Do you use the most recent version `21.10.30`? Because I already [submitted a fix yesterday](https://twitter.com/Kwaschny/status/1454460840661356549).

To force extension updates on Chrome, go to `chrome://extensions/` (type in address bar), check the top right checkbox `Developer mode` and then click on the now appearing `Update` button. You can disable the developer mode after this.

**Comment by djcline23** [comment]
Yeah, think it's the same and working now with the latest version. Thanks.
