### ISSUE TITLE
Blacklisted Channels does not work well with user names such as Japanese

### ISSUE THREAD

**Issue by zamrumrvo** [kwaschny/unwanted-twitch#83]
Blacklisted Channels does not work well with user names such as Japanese.
If I enter a user name or user ID, or both, execution does not work. If I enter both, the target is displayed without a space. That's probably the reason, I think.

**Comment by kwaschny** [comment]
Yes, there have been inconsistencies with what name representation is shown on the directory. I prioritize whatever is used as the link name (`twitch.tv/xxx`), but due to the frequent changes, these things can easily break without being immediately noticable.

Can you provide a list of such channels and/or categories that tend to be inconsistent and not detected/blocked everytime/everywhere?

**Comment by zamrumrvo** [comment]
Do you want me to provide my actual block list? It is difficult to disclose it in terms of personal information.
If it is difficult to improve without disclosure, there is no choice but to give up. I've already talked about how the list looks. 
Thank you very much.

**Comment by kwaschny** [comment]
> Do you want me to provide my actual block list?

No, any channel that causes the issue is good enough. I just need an example to reproduce the problem. I checked the Japanese, Chinese and Korean directory and wasn't able to reproduce your problem.

But I might have misunderstood your initial post. Are you talking about _manually_ adding names to the list that do not match the exact spelling on twitch.tv? Because all channel names require a "latin-friendly" representation.

Example: `蛇足 (dasoku_aniki)`  
that's `<unicode_string> (<latin_friendly>)`

The blacklist only blocks exact matches. Neither `蛇足`  nor `dasoku_aniki` will work on their own. It needs to be `蛇足 (dasoku_aniki)`.

**Comment by kwaschny** [comment]
Whitespaces in channel names are being removed when adding them manually. That's the bug. Sorry for being dull. 😊
