### ISSUE TITLE
Hitting max storage at 186k blocked channels?

### ISSUE THREAD

**Issue by djcline23** [kwaschny/unwanted-twitch#89]
I'm using chrome version 103.0.5060.134, I also have Adblock Plus if that matters, Unwanted Twitch version 22.7.20, and Synchronize via Cloud is NOT checked. I import the attached file (uploaded as text because it didn't want to take json) - note 186k blocked channels - and click Save. In twitch, click Manage Blacklist - note only 100 blocked channels now. Like local storage is being overflowed or something(?) so almost all the blocked channels disappear, and all entries in the other columns disappear.

While trying to capture info for this report I did the import maybe like 8 times, and now I see an Out of Memory message in chrome. After that, trying to click Manage Blacklist does nothing. So some other clue that something is going bad with memory use? I also recently had to restart the computer because I was running out of memory, so it seems like there might be a leak - maybe related, maybe separate problem?
[UnwantedTwitch_Blacklist.txt](https://github.com/kwaschny/unwanted-twitch/files/9227927/UnwantedTwitch_Blacklist.txt)

**Comment by djcline23** [comment]
It seems to be working okay in Firefox though.

**Comment by kwaschny** [comment]
> seems to be working okay in Firefox though.

That's because Firefox doesn't apply as many memory constraints and also seems to be better at rendering big documents such as the management view with this many elements. Even `chrome.storage.local` has a maximum of 5 MB by default. I think it's possible to disable this limit when requesting `unlimitedStorage` permission though.

I cannot even load your list in Chrome as it always hits one of the memory or CPU constraints after a few seconds. The question is: what do you expect me to do? Your use case is kinda exotic, too exotic for me to be honest with you.

**Comment by djcline23** [comment]
Haha well it's good to know there's nothing to do. So far I'm doing fine on firefox, or now I know the thing to do is start trying to hack the browser itself. :P

**Comment by djcline23** [comment]
FYI firefox only made it another couple thousand before it had the same problem. I'm trying with unlimitedStorage and upping the maximum local storage size now - hopefully no more problems.
