### ISSUE TITLE
Filter by number of viewers

### ISSUE THREAD

**Issue by Manu-SA** [kwaschny/unwanted-twitch#91]
Hello first of all thx for your addon it's really help me to find some new streamers but i have one problem : the problem is that i need to scroll during a lot of time to reach streamer that have 5-10 viewers. So i have a suggestion, it's to add a slider to select the range of stream viewers that i want to see, for example a button like that : 

![image](https://user-images.githubusercontent.com/95525454/183757308-e1ebc616-365e-453a-bdd2-5c0fa5617f0c.png)

I don't know if it's possible/hard but thx for your time and have a good day
( i hope it will be clear because my english is not very good )

**Comment by kwaschny** [comment]
This has been requested/suggested one or two times now, see #49. While technically possible, I don't think this will yield an acceptable user experience. The filter will constantly fetch new channels until the threshold is reached, which will take either a lot of time or simply flag you as a bot due to the high amount of consecutive requests. I remember seeing captchas when scrolling too fast through a directory. They have loosen up the timing since then, but still.

[It seems to be possible via API](https://twitch-tools.rootonline.de/channel_previews.php), but that's just not how this extension works.

**Comment by Manu-SA** [comment]
Ok I understand, this site seems to be good for what i want to do, just have to blacklist again the different games that i don't want but it seems to be good

**Comment by kwaschny** [comment]
See [project status](https://github.com/kwaschny/unwanted-twitch#project-status).
