### ISSUE TITLE
A bug that ignore long note "ー"

### ISSUE THREAD

**Issue by zamrumrvo** [kwaschny/unwanted-twitch#96]
If the screen name contains a long note "ー", the long note is ignored and does not appear correctly in the list. This is just one example, but it is possible that other symbols may not be displayed.

eg: かーめん -> かめん

**Comment by kwaschny** [comment]
This is actually intended behavior, introduced with 25def56a98cd64b515e8bd134319c3f0a1f57bf7 in version `22.8.14`. Added items are normalized and have their diacritics removed. The same is applied to items that are matched against them in the directory. An item with `かーめん` will be blocked just like an item with `かめん`.

This has been introduced to deal with different spelling, especially due to the custom tags. It should not affect the semantics. I can't tell if your example are two different things and one should be blocked while the other one should not. So did you report because that's exactly the case or because you observed an input not being stored as-is?

**Comment by zamrumrvo** [comment]
I understand the intended action, but it feels strange that the list is not accurate. An account may have put that symbol in its screen name for display purposes. I don't understand why you deliberately intended to ignore symbols.
I feel like it's going to be a little inconvenient that when I check the screen names and re-edit the list, they're different from the actual screen names (You can just check the ID, but the user will trust that the screen name is accurate)

Well, if it actually works, there's no problem, but it's a little weird.

**Comment by kwaschny** [comment]
> I don't understand why you deliberately intended to ignore symbols.

For the same reason I ignore upper-/lowercase letters: they are not beneficial to what the user wants. Diacritics are used for pronunciation. They have no meaning for a blacklist that filters content based on written description and keywords. When Twitch came up with "invent your own tags", there has been a wave of _"I blocked this term, but it still shows up!"_ reports - simply because the exact symbols mattered in the past. If I type `espanol`, I also mean `español`. Search/Match functions work like this, everywhere.

> I feel like it's going to be a little inconvenient that when I check the screen names and re-edit the list, they're different from the actual screen names

That might be more of a language specific issue then. Most content on Twitch is still Indo-European and thus using the latin alphabet. I see your point, but I'd consider this more of an edge case for now. (To other readers/users) Feel free to voice your opinions here. Maybe I'm just wrong and disregarding diacritics is doing more harm than good.

**Comment by zamrumrvo** [comment]
I previously reported a bug that didn't show up if you included screen names, and it's a little disappointing that you're also not very interested in other languages.
Anyway, now I know this is not a bug. Thank you for your answer.
